# Generated by Django 4.2.5 on 2024-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='nft_token_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
