# Generated by Django 4.2.5 on 2024-05-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_alter_order_nft_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_supplier_address', models.CharField(max_length=2000)),
                ('amount', models.FloatField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
        ),
    ]
