# Generated by Django 4.2.5 on 2024-05-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_supplyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chain_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
