# Generated by Django 4.2.5 on 2023-09-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconf', '0003_alter_user_address_alter_user_craft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'consumer'), ('artisan', 'artisan'), ('admin', 'admin'), ('wholesaler', 'wholesaler')], max_length=30),
        ),
    ]
