# Generated by Django 4.2.5 on 2024-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconf', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'consumer'), ('artisan', 'artisan'), ('admin', 'admin'), ('wholesaler', 'wholesaler'), ('supplyChain', 'supplyChain')], max_length=30),
        ),
    ]
