# Generated by Django 4.2.5 on 2024-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconf', '0005_user_company_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='craft',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gstin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
