# Generated by Django 4.2.5 on 2024-05-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconf', '0006_alter_user_craft_alter_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
